return {
  'MeanderingProgrammer/dashboard.nvim',
  event = 'VimEnter',
  dependencies = {
    { 'MaximilianLloyd/ascii.nvim', dependencies = { 'MunifTanjim/nui.nvim' } },
  },
  config = function()
    require('dashboard').setup({
      header = require('ascii').art.text.neovim.sharp,
      date_format = '%d.%m.%Y %H:%M',
      directories = {
        '~/.config/nvim',
        '~/.config',
        '~/.dots',
        '~/code',
      },
      footer = {
        'version',
        'startuptime',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
      },
    })
  end,
}
